version: '3.8'
 
services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www/html 
    ports:
      - "8001:80"
    depends_on:
      - mysql
 
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: deliverium
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
 
volumes:
  mysql_data: